
package com.ust.calc.calculadora.datasource.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.stereotype.Component;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@Component
@WebServiceClient(name = "HelloService", targetNamespace = "http://service.ws.sample/", wsdlLocation = "http://localhost:8080/datasource-ws/data?WSDL")
public class DataOperationPortImplService
    extends Service implements DataOperationPortService
{

    private final static URL DATAOPERATIONPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAOPERATIONPORTIMPLSERVICE_EXCEPTION;
    private final static QName DATAOPERATIONPORTIMPLSERVICE_QNAME = new QName("http://service.ws.sample/", "HelloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/datasource-ws/data?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAOPERATIONPORTIMPLSERVICE_WSDL_LOCATION = url;
        DATAOPERATIONPORTIMPLSERVICE_EXCEPTION = e;
    }

    public DataOperationPortImplService() {
        super(__getWsdlLocation(), DATAOPERATIONPORTIMPLSERVICE_QNAME);
    }

    public DataOperationPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAOPERATIONPORTIMPLSERVICE_QNAME, features);
    }

    public DataOperationPortImplService(URL wsdlLocation) {
        super(wsdlLocation, DATAOPERATIONPORTIMPLSERVICE_QNAME);
    }

    public DataOperationPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAOPERATIONPORTIMPLSERVICE_QNAME, features);
    }

    public DataOperationPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataOperationPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataOperation
     */
    @WebEndpoint(name = "HelloPort")
    public DataOperation getDataOperationPortImplPort() {
        return super.getPort(new QName("http://service.ws.sample/", "HelloPort"), DataOperation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataOperation
     */
    @WebEndpoint(name = "HelloPort")
    public DataOperation getDataOperationPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.sample/", "HelloPort"), DataOperation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAOPERATIONPORTIMPLSERVICE_EXCEPTION!= null) {
            throw DATAOPERATIONPORTIMPLSERVICE_EXCEPTION;
        }
        return DATAOPERATIONPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
