
package com.ust.calc.calculadora.datasource.api;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataOperation", targetNamespace = "http://service.ws.sample/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataOperation {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ust.datasource.api.Data
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createData", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.CreateData")
    @ResponseWrapper(localName = "createDataResponse", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.CreateDataResponse")
    public Data createData(
        @WebParam(name = "arg0", targetNamespace = "")
        Data arg0);

    /**
     * 
     * @param id
     * @return
     *     returns com.ust.datasource.api.Data
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readData", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.ReadData")
    @ResponseWrapper(localName = "readDataResponse", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.ReadDataResponse")
    public Data readData(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param dni
     * @return
     *     returns com.ust.datasource.api.Data
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByDni", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.FindByDni")
    @ResponseWrapper(localName = "findByDniResponse", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.FindByDniResponse")
    public Data findByDni(
        @WebParam(name = "dni", targetNamespace = "")
        String dni);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<com.ust.datasource.api.Data>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByName", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.FindByNameResponse")
    public List<Data> findByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ust.datasource.api.Data
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.UpdateResponse")
    public Data update(
        @WebParam(name = "arg0", targetNamespace = "")
        Data arg0);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.DeleteResponse")
    public void delete(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @return
     *     returns java.util.List<com.ust.datasource.api.Data>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.ws.sample/", className = "com.ust.datasource.api.FindAllResponse")
    public List<Data> findAll();

}
